Digit Recognizer

In [1]:
# !kaggle competitions download -c digit-recognizer

In [2]:
# !pip install kaggle

In [3]:
# import os
# import zipfile

# zip_file_path = 'digit-recognizer.zip'
# folder_name = 'digit-recognizer'

# # Create the folder if it doesn't exist
# if not os.path.exists(folder_name):
#     os.makedirs(folder_name)

# with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
#     zip_ref.extractall(folder_name)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
mnist=pd.read_csv('digit-recognizer/train.csv')
mnist

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
import os
print(os.listdir('digit-recognizer'))

['sample_submission.csv', 'test.csv', 'train.csv']

In [7]:
import os
print(os.getcwd())  # Print current working directory
print(os.listdir()) # List files in the current directory

c:\MACHINE LEARNING PRACTICE\handson-ml3\ch3\Digit Recognizer
['digit-recognizer', 'digit-recognizer.zip', 'kaggle_digit_recognizer_mnist.ipynb', 'sample_submission.csv', 'submission folder']

In [8]:
mnist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [9]:
mnist.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [10]:
mnist.index

RangeIndex(start=0, stop=42000, step=1)

In [11]:
mnist['label'].describe()

count    42000.000000
mean         4.456643
std          2.887730
min          0.000000
25%          2.000000
50%          4.000000
75%          7.000000
max          9.000000
Name: label, dtype: float64

In [12]:
mnist['label'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 42000 entries, 0 to 41999
Series name: label
Non-Null Count  Dtype
--------------  -----
42000 non-null  int64
dtypes: int64(1)
memory usage: 328.3 KB

In [13]:
x=mnist.iloc[:,1:]
y=mnist.iloc[:,0].to_frame()

In [14]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(mnist.iloc[:,1:],mnist.iloc[:,0].to_frame(),random_state=42,test_size=.2,stratify=y)

In [15]:
y_train['label'].value_counts()/len(y_train)

label
1    0.111518
7    0.104792
3    0.103601
9    0.099702
2    0.099464
6    0.098512
0    0.098363
4    0.096964
8    0.096726
5    0.090357
Name: count, dtype: float64

In [16]:
y_test['label'].value_counts()/len(y_test)

label
1    0.111548
7    0.104762
3    0.103571
9    0.099762
2    0.099405
6    0.098452
0    0.098452
4    0.096905
8    0.096786
5    0.090357
Name: count, dtype: float64

In [17]:
x_train

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
5254,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38950,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35230,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13983,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32984,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24079,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16830,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22509,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30311,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13153,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
y_train

       label
5254       2
38950      3
35230      6
13983      4
32984      0
...      ...
24079      5
16830      8
22509      1
30311      8
13153      0

[33600 rows x 1 columns]

In [19]:
# using knn_classifier
from sklearn.neighbors import KNeighborsClassifier

knn_clf=KNeighborsClassifier()

In [ ]:
from sklearn.model_selection import cross_val_score

cross_val_score(knn_clf,x_train,y_train,cv=3,scoring='accuracy')

Scaling the features

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.fit(x_test)

In [22]:
#as range is less scaling not a good idea it could introduce noise

In [ ]:
knn_clf2=KNeighborsClassifier()
cross_val_score(knn_clf2,x_train_scaled,y_train,cv=3,scoring='accuracy')

In [24]:
from sklearn.model_selection import GridSearchCV

grid_params=[{'n_neighbors':[3,4,5,6],'weights':["uniform","distance"]}]

knn_clf3=KNeighborsClassifier()
grid_search=GridSearchCV(knn_clf3,cv=5,param_grid=grid_params)

In [ ]:
grid_search.fit(x_train,y_train)

In [26]:
grid_search.best_params_

{'n_neighbors': 4, 'weights': 'distance'}

In [27]:
grid_search.best_score_

0.9680357142857143

In [28]:
acccuracy_from_best_estimator=grid_search.score(x_test,y_test)
acccuracy_from_best_estimator

0.9688095238095238

Prediction 1

In [29]:
test_set=pd.read_csv('digit-recognizer/test.csv')
test_set

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
prediction=grid_search.predict(test_set)
prediction

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [31]:
submission1=pd.DataFrame(
    {
        'ImageId':test_set.index+1,
        'Label':prediction
    }
)
submission1.set_index('ImageId',inplace=True)
submission1.to_csv('submission folder/submission1.csv')

TRAINING THE BEST MODEL WITH FULL DATASET

In [32]:
best_estimator=grid_search.best_estimator_

In [33]:
best_estimator.fit(x,y)
prediction2=best_estimator.predict(test_set)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [34]:
submission2=pd.DataFrame(
    {
        'ImageId':test_set.index+1,
        'Label':prediction2
    }
)
submission2.set_index('ImageId',inplace=True)
submission2.to_csv('submission folder/submission2.csv')

Trainning grid search again on full data and doing the prediction

In [ ]:
# grid_search.fit(x,y)
# prediction3=grid_search.predict(test_set)

In [36]:

# submission3=pd.DataFrame(
#     {
#         'ImageId':test_set.index+1,
#         'Label':prediction3
#     }
# )
# submission3.set_index('ImageId',inplace=True)
# submission3.to_csv('submission folder/submission3.csv')

In [ ]:
submission1=pd.read_csv('submission folder\submission1.csv')
submission2=pd.read_csv('submission folder\submission2.csv')
submission3=pd.read_csv('submission folder\submission3.csv')

In [ ]:
(submission1['Label']-submission2).sum()

In [ ]:
(submission1['Label'].astype('int8')-submission3.astype('int8')).sum()

In [ ]:
(submission2['Label'].astype('int8')-submission3.astype('int8')).sum()

Doing Data Augmentation and training the model again

In [ ]:
def shift_image(image,dx,dy):
    image=image.reshape(28,28)
    shifted_image=shift(image,[dy,dx],mode='constant',cval=0)
    image=shifted_image.reshape([-1])
    print(image.shape)
    return image

In [ ]:
x_augmented = [image for image in x]
y_augmented = [label for label in y]

for dx, dy in ((-1, 0), (1, 0), (0, 1), (0, -1)):
    for image, label in zip(x_train, y_train):
        x_augmented.append(shift_image(image, dx, dy))
        y_augmented.append(label)

x_augmented = np.array(x_augmented)
y_augmented = np.array(y_augmented)

In [ ]:
best_estimator.fit(x_augmented,y_augmented)
prediction4=best_estimator.predict(test_set)

In [ ]:
submission4=pd.DataFrame(
    {
        'ImageId':test_set.index+1,
        'Label':prediction4
    }
)
submission4.set_index('ImageId',inplace=True)
submission4.to_csv('submission folder/submission4.csv')

In [ ]:
hello